"""Add multi-tenancy support

Revision ID: ae30a1b97233
Revises: 
Create Date: 2025-11-04 16:09:08.308155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae30a1b97233'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_records_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('ad_cost', sa.Float(), nullable=True),
    sa.Column('conversion_sales', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_records_legacy_date'), 'ad_records_legacy', ['date'], unique=False)
    op.create_index(op.f('ix_ad_records_legacy_id'), 'ad_records_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_ad_records_legacy_store'), 'ad_records_legacy', ['store'], unique=False)
    op.create_table('product_master_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_master_legacy_id'), 'product_master_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_product_master_legacy_product_code'), 'product_master_legacy', ['product_code'], unique=True)
    op.create_table('sales_records_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_records_legacy_date'), 'sales_records_legacy', ['date'], unique=False)
    op.create_index(op.f('ix_sales_records_legacy_id'), 'sales_records_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_sales_records_legacy_store'), 'sales_records_legacy', ['store'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('integrated_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sales_amount', sa.Float(), nullable=True),
    sa.Column('sales_quantity', sa.Integer(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('total_sales_quantity', sa.Integer(), nullable=True),
    sa.Column('ad_cost', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ad_sales_quantity', sa.Integer(), nullable=True),
    sa.Column('conversion_sales', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('margin_amount', sa.Float(), nullable=True),
    sa.Column('margin_rate', sa.Float(), nullable=True),
    sa.Column('fee_rate', sa.Float(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('actual_margin_rate', sa.Float(), nullable=True),
    sa.Column('cost_rate', sa.Float(), nullable=True),
    sa.Column('ad_cost_rate', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'option_id', 'date', name='uix_tenant_option_date')
    )
    op.create_index('idx_tenant_option_date', 'integrated_records', ['tenant_id', 'option_id', 'date'], unique=False)
    op.create_index(op.f('ix_integrated_records_date'), 'integrated_records', ['date'], unique=False)
    op.create_index(op.f('ix_integrated_records_id'), 'integrated_records', ['id'], unique=False)
    op.create_index(op.f('ix_integrated_records_option_id'), 'integrated_records', ['option_id'], unique=False)
    op.create_index(op.f('ix_integrated_records_product_name'), 'integrated_records', ['product_name'], unique=False)
    op.create_index(op.f('ix_integrated_records_tenant_id'), 'integrated_records', ['tenant_id'], unique=False)
    op.create_table('product_margins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('margin_amount', sa.Float(), nullable=True),
    sa.Column('margin_rate', sa.Float(), nullable=True),
    sa.Column('fee_rate', sa.Float(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'option_id', name='uix_tenant_option')
    )
    op.create_index(op.f('ix_product_margins_id'), 'product_margins', ['id'], unique=False)
    op.create_index(op.f('ix_product_margins_option_id'), 'product_margins', ['option_id'], unique=False)
    op.create_index(op.f('ix_product_margins_product_name'), 'product_margins', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_margins_tenant_id'), 'product_margins', ['tenant_id'], unique=False)
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('sales_filename', sa.String(), nullable=False),
    sa.Column('ads_filename', sa.String(), nullable=False),
    sa.Column('margin_filename', sa.String(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('matched_with_ads', sa.Integer(), nullable=True),
    sa.Column('matched_with_margin', sa.Integer(), nullable=True),
    sa.Column('fully_integrated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_index(op.f('ix_upload_history_tenant_id'), 'upload_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_upload_history_uploaded_at'), 'upload_history', ['uploaded_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('additional_data', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_tenant_user', 'audit_logs', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uix_user_tenant')
    )
    op.create_index(op.f('ix_tenant_memberships_id'), 'tenant_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_user', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upload_history_uploaded_at'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_tenant_id'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.drop_table('upload_history')
    op.drop_index(op.f('ix_product_margins_tenant_id'), table_name='product_margins')
    op.drop_index(op.f('ix_product_margins_product_name'), table_name='product_margins')
    op.drop_index(op.f('ix_product_margins_option_id'), table_name='product_margins')
    op.drop_index(op.f('ix_product_margins_id'), table_name='product_margins')
    op.drop_table('product_margins')
    op.drop_index(op.f('ix_integrated_records_tenant_id'), table_name='integrated_records')
    op.drop_index(op.f('ix_integrated_records_product_name'), table_name='integrated_records')
    op.drop_index(op.f('ix_integrated_records_option_id'), table_name='integrated_records')
    op.drop_index(op.f('ix_integrated_records_id'), table_name='integrated_records')
    op.drop_index(op.f('ix_integrated_records_date'), table_name='integrated_records')
    op.drop_index('idx_tenant_option_date', table_name='integrated_records')
    op.drop_table('integrated_records')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sales_records_legacy_store'), table_name='sales_records_legacy')
    op.drop_index(op.f('ix_sales_records_legacy_id'), table_name='sales_records_legacy')
    op.drop_index(op.f('ix_sales_records_legacy_date'), table_name='sales_records_legacy')
    op.drop_table('sales_records_legacy')
    op.drop_index(op.f('ix_product_master_legacy_product_code'), table_name='product_master_legacy')
    op.drop_index(op.f('ix_product_master_legacy_id'), table_name='product_master_legacy')
    op.drop_table('product_master_legacy')
    op.drop_index(op.f('ix_ad_records_legacy_store'), table_name='ad_records_legacy')
    op.drop_index(op.f('ix_ad_records_legacy_id'), table_name='ad_records_legacy')
    op.drop_index(op.f('ix_ad_records_legacy_date'), table_name='ad_records_legacy')
    op.drop_table('ad_records_legacy')
    # ### end Alembic commands ###
